package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSeckill;
import org.linlinjava.litemall.db.domain.LitemallSeckillExample;

public interface LitemallSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    long countByExample(LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int insert(LitemallSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSeckill selectOneByExample(LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSeckill selectOneByExampleSelective(@Param("example") LitemallSeckillExample example, @Param("selective") LitemallSeckill.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallSeckill> selectByExampleSelective(@Param("example") LitemallSeckillExample example, @Param("selective") LitemallSeckill.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    List<LitemallSeckill> selectByExample(LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSeckill selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSeckill.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    LitemallSeckill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallSeckill selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSeckill record, @Param("example") LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSeckill record, @Param("example") LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}