package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallWithdrawApply;
import org.linlinjava.litemall.db.domain.LitemallWithdrawApplyExample;

public interface LitemallWithdrawApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    long countByExample(LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int insert(LitemallWithdrawApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWithdrawApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWithdrawApply selectOneByExample(LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWithdrawApply selectOneByExampleSelective(@Param("example") LitemallWithdrawApplyExample example, @Param("selective") LitemallWithdrawApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallWithdrawApply> selectByExampleSelective(@Param("example") LitemallWithdrawApplyExample example, @Param("selective") LitemallWithdrawApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    List<LitemallWithdrawApply> selectByExample(LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWithdrawApply selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWithdrawApply.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    LitemallWithdrawApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWithdrawApply record, @Param("example") LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWithdrawApply record, @Param("example") LitemallWithdrawApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWithdrawApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_withdraw_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWithdrawApply record);
}